config/routes.rb
Rails.application.routes.draw do
  get '/posts/:id/md', to: 'posts#markdown'
  get '/posts/markdown', to: 'posts#helpmarkdown'
  get '/posts/howtomarkdown', to: 'posts#howtomarkdown'
  get '/home', to: 'home#show'
  get '/edit', to: 'test_sessions#edit'

  get '/test_papers/', to: 'test_papers#show',:as => :test_papers_page
  post '/test_papers/', to: 'users#home'
  post '/test_papers/final', to: 'test_papers#final'

  post '/test_sessions/update', to: 'test_sessions#update'
  post '/test_sessions/create', to: 'test_sessions#create'
  post '/test_sessions/create_test_paper', to: 'test_sessions#create_test_paper'
  post '/posts/create', to: 'posts#create'
  post '/posts/update', to: 'posts#update'
  get '/posts/:id/edit', to: 'posts#edit'
  post '/search/:id', to: 'search#index', :as => :search_page
  get '/users/home', to: 'users#home'
  post '/users/update', to: 'users#update'
  post '/exams/update', to: 'exams#update'
  post '/exams/create', to: 'exams#create'
  post '/jquery', to: 'search_jquery#getQuestion'
  get '/users/:id', to: 'users#show'

  #get '/exams/', to:'exams#show', :as :exams_page
  resources :posts
  resources :tests
  resources :test_sessions
  resources :exams

  root 'home#show', :as => :home_page
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'quiz'=>'tests#quiz'
  resources :test
  
end

app/models/test_paper.rb
class TestPaper < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :exam
  belongs_to :test_session
end

app/controllers/test_papers_controller.rb
class TestPapersController < ApplicationController
    include Clearance::Controller
    skip_before_action :verify_authenticity_token
    def toHome
        redirect_to home_path
    end


    def show
        @title = Exam 
        @test_session_id = TestPaper.where(user_id: current_user.id).last.test_session_id

        @timeRemaining = 0
        if allow_examinations
            if TestPaper.where(user_id: current_user.id, test_session_id: @test_session_id).last.point != nil 
                redirect_to  '/users/home'
            else
                public_time = TestSession.find(@test_session_id).time_public.utc
                current_time = Time.now.utc
                ts = TestSession.find(@test_session_id).time_remaining*60
                time = ts.to_i-(current_time-public_time).to_i
                @timeRemaining = time
            end
        else
            redirect_to home_path
        end
    end

    def allow_examinations
        if signed_in?
            if SessionMember.where(user_id: current_user.id, test_session_id: @test_session_id).exists?
                return true
            else
                return false
            end
        else
            return false
        end
    end

    def create
       redirect_to home_path
    end

    def final
        arrayAnswer = params[:answers]
        tsid = TestPaper.last.test_session_id
        ts = TestSession.find(tsid)
        _exam_ids = ts.exams.ids 
        list_questionID = []
        _exam_ids.each do |id|
            list_temp = Exam.find(id).list_questions.split(",")
            list_questionID.concat list_temp
        end

        list_anwsers = []
        list_questionID.each do |li|
            temp = li.to_i
            list_anwsers.push(Question.find(temp).key)
        end
        numCorrect = 0
        i = 0 
        while i < arrayAnswer.length
            if arrayAnswer[i]== list_anwsers[i]
                numCorrect+=1
            end
            i+=1
        end
        tp = TestPaper.where(user_id:current_user.id,test_session_id:tsid)
        tp.update(content:arrayAnswer,point:numCorrect)

        redirect_to  home_path
    end
end

app/helpers/test_papers_helper.rb
module TestPapersHelper
    def getAllQuestionID(_test_session_id)
        tsid = _test_session_id.to_i
        ts = TestSession.find(tsid)
        _exam_ids = ts.exams.ids 
        list_questionID = []
        _exam_ids.each do |id|
            list_temp = Exam.find(id).list_questions.split(",")
            list_questionID.concat list_temp
        end
        return list_questionID
    end
end

app/views/test_papers/_exams.html.erb
<%= form_for :exam, url: test_papers_page_path do |form| %>
    <script>
        var upgradeTime = <%= @timeRemaining %> ;
        var seconds = upgradeTime;
        function timer() {
            var days        = Math.floor(seconds/24/60/60);
            var hoursLeft   = Math.floor((seconds) - (days*86400));
            var hours       = Math.floor(hoursLeft/3600);
            var minutesLeft = Math.floor((hoursLeft) - (hours*3600));
            var minutes     = Math.floor(minutesLeft/60);
            var remainingSeconds = seconds % 60;
        function pad(n) {
            return (n < 10 ? "0" + n : n);postSearch
        }
        document.getElementById('countdown').innerHTML = pad(hours) + ":" + pad(minutes) + ":" + pad(remainingSeconds);
        if (seconds == 0) {
            clearInterval(countdownTimer);
            document.getElementById('countdown').innerHTML = "Hết giờ làm bài!";
             var element = $(".custom-control-label");
                var arrayAnswer = [];
                var checkbox = $(".custom-control-input");
                for(var i=0;i<checkbox.length/4;i++){
                    for(var j=0;j<4;j++){
                        if(checkbox[i*4+j].checked==true){
                            arrayAnswer[i]=element[i*4+j].id;
                        }
                    }
                    if(arrayAnswer[i]==null){
                        arrayAnswer[i]="x";
                    }
                }
                $.post('/test_papers/final',
                        {answers: arrayAnswer},
                    );
        } else {
        seconds--;
        }
        }
        var countdownTimer = setInterval('timer()', 1000);
    </script>
    <style type="text/css">
        .flip-clock-wrapper{
            
            align:left;
            background: aquamarine;
            font-size: 3vh;
            position: fixed;
            cursor: pointer;
            -webkit-user-select: none;
            border:2px solid aqua;
            color: darkslategray;
        }
        .text-right{
            margin-right: 90px;
            
        }
    </style>
    
    <div class="col text-right">
            <span id="countdown" class="timer flip-clock-wrapper" type="" name="exam[save]" value="cc"></span>
        </div>
        <% @list = getAllQuestionID(@test_session_id)%>
    <% $i=0 %>
    <% @list.each do |li|%> 
      <% $i+=1 %>
        <% if $i%2==0 %>
            <section class="container bg-success" data="<%= li%>">
                <h4> 問題:<%= $i%> </h4>
                <h4><%= markdown(Question.find(li).content) %></h4>
                    <% @temp=eval(Question.find(li).answers)%>
                <div class="custom-control custom-radio">
                    <label class="custom-control-label" id="ア">
                    <input type="radio" class="custom-control-input" name=<%= $i %>> <%= @temp[:a] %></label>
                </div>
                <div class="custom-radio custom-control">
                    <label class="custom-control-label" id="イ" >
                    <input type="radio" class="custom-control-input" name=<%= $i %>> <%= @temp[:i] %></label>
                </div>
                <div class="custom-radio custom-control ">
                    <label class="custom-control-label" id="ウ" >
                    <input type="radio" class="custom-control-input" name=<%= $i %>> <%= @temp[:u]%></label>
                </div>
                <% if @temp[:e].blank? == false %>
                <div class="custom-radio custom-control">
                    <label class="custom-control-label" id="エ" >
                    <input type="radio" class="custom-control-input" name=<%= $i %>> <%= @temp[:e]%></label>
                </div>
                <% end %>
            </section>
        <% else %>
            <section class="container bg-warning" data="<%= li%>">
                <h4> 問題:<%= $i%> </h4>
                <h4><%= markdown(Question.find(li).content) %></h4>
                    <% @temp=eval(Question.find(li).answers)%>
                <div class="custom-control custom-radio">
                    <label class="custom-control-label" id="ア">
                    <input type="radio" class="custom-control-input" name=<%= $i %>> <%= @temp[:a] %></label>
                </div>
                <div class="custom-radio custom-control">
                    <label class="custom-control-label" id="イ" >
                    <input type="radio" class="custom-control-input" name=<%= $i %>> <%= @temp[:i] %></label>
                </div>
                <div class="custom-radio custom-control ">
                    <label class="custom-control-label" id="ウ" >
                    <input type="radio" class="custom-control-input" name=<%= $i %>> <%= @temp[:u]%></label>
                </div>
                <% if @temp[:e].blank? == false %>
                <div class="custom-radio custom-control">
                    <label class="custom-control-label" id="エ" >
                    <input type="radio" class="custom-control-input" name=<%= $i %>> <%= @temp[:e]%></label>
                </div>
                <% end %>
            </section>
        <% end %>

    <% end %>

    </br>

    
    <button class="btn btn-primary btn-block" id="submit-btn" name="exams">Nộp bài</button>

<% end %>

app/views/test_papers/show.html.erb
<%= render partial: '/test_papers/exams'%>